name: lemmy_api_client
version: 0.1.1
homepage: https://github.com/krawieck/lemmy_api_client
description: Future-based API client for Lemmy

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.2
  meta: ^1.2.2

dev_dependencies:
  test: ^1.3.0
  effective_dart: ^1.0.0
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
