name: lemmy_api_client
version: 0.12.0
homepage: https://github.com/krawieck/lemmy_api_client
description: Future-based http client for the Lemmy API. Provides an easy interface and statically typed responses.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.2
  meta: ^1.3.0
  freezed_annotation: ^0.12.0
  web_socket_channel: ^1.2.0

dev_dependencies:
  test: ^1.16.5
  json_serializable: ^3.5.1
  build_runner: ^1.11.5
  freezed: ^0.12.7
