name: lemmy_api_client
version: 0.2.0
homepage: https://github.com/krawieck/lemmy_api_client
description: Future-based http client for the Lemmy API. Provides an easy interface and statically typed responses.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  http: ^0.12.2
  meta: ^1.1.8

dev_dependencies:
  test: ^1.3.0
  effective_dart: ^1.0.0
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
