name: lemmy_api_client
version: 0.18.0
homepage: https://github.com/krawieck/lemmy_api_client
description: Future-based http client for the Lemmy API. Provides an easy interface and statically typed responses.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.3.0
  http: ^0.13.1
  freezed_annotation: ^1.0.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.4
  freezed: ^1.0.0
  json_serializable: ^6.0.0
  test: ^1.16.8
