name: lemmy_api_client
version: 0.12.0
homepage: https://github.com/krawieck/lemmy_api_client
description: Future-based http client for the Lemmy API. Provides an easy interface and statically typed responses.

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  http: ^0.13.1
  freezed_annotation: ^0.14.1
  web_socket_channel: ^2.0.0

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
  json_serializable: ^4.1.0
  test: ^1.16.8
