name: cd

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - uses: actions/checkout@v2

      - name: Inject pub.dev credentials
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          mkdir -p ~/.config/dart/
          echo $PUB_CREDENTIALS > ~/.config/dart/pub-credentials.json

      - name: Publish to pub.dev
        run: dart pub publish -f
