name: cd

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1.6
        with:
          sdk: stable

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.yaml', 'pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Get dependencies
        run: dart pub get

      - name: Inject pub.dev credentials
        env:
          PUB_CREDENTIALS: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          mkdir -p ~/.config/dart/
          echo $PUB_CREDENTIALS > ~/.config/dart/pub-credentials.json

      - name: Publish to pub.dev
        run: dart pub publish -f
