name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: pub get

      # disabled because: https://github.com/dart-lang/sdk/issues/25551
      # 4.5yo bug...
      # - name: Run lints
      #   run: dartanalyzer --fatal-warnings --fatal-infos .

      - name: Run tests
        run: pub run test
