name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: cedx/setup-dart@v2
        with:
          release-channel: stable

      - uses: actions/checkout@v2

      - name: Get dependencies
        run: dart pub get

      - name: Check formatting
        run: dart format --fix --set-exit-if-changed -o none .

      - name: Run lints
        run: dart analyze --fatal-warnings --fatal-infos

      - name: Run tests
        run: dart test
